### ISSUE TITLE
Wrapper execution failing at aggregation of monthlySeasonalityIndices

### ISSUE THREAD

**Issue by CaitlinA** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#26]
The error returned is a variation of that below:

    Error in seq_len(ncol(vwc)) : 
    argument must be coercible to non-negative integer.

I have received the error when the following aggregations are turned on:
* monthlySeasonalityIndices
* dailySWPextremes
* dailyWetDegreeDays
* dailyThermalDrynessStartEnd
* dailyThermalSWPConditionCount
* monthlySWPdryness
* dailySWPdrynessANDwetness
* dailySuitablePeriodsDuration
* dailySWPdrynessDurationDistribution
* dailySWPdrynessEventSizeDistribution
* dailyThermalDrynessStress
* monthlySWPmatric

@dschlaep @alexreeder

**Comment by dschlaep** [comment]
The issue arose because of a bug in the functions 'pdf_to_vwc' and 'pdf_to_swp'.

Because of the ifelse(), they didn't return a correctly dimensioned object in all cases. I have fixed this bug and am currently re-writing the functions 'VWCtoSWP' and 'SWPtoVWC' as well as writing unit tests for them.
