### ISSUE TITLE
Replace 'temp_timer.csv' with database

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#44]
The problem is that all workers are writing simultaneously to ‘temp_timer.csv’ and they can and at times do overwrite each other. This causes problems because the code relies on an intact file to detect which simulation runs have already completed.

Idea: replace 'temp_timer.csv' with a database with a table that lists all P_id (=jobs) and flags if a job is successfully completed, failed, checked-out/in-progress (on a worker), or awaiting processing.

**Comment by alexreeder** [comment]
Test on Yellowstone was successful. There were some issues during tests (like a crash, actually twice during aggregations) but a third run continued to finish.

**Comment by alexreeder** [comment]
The crashes were caused by worker disconnects
[1] "Aggregation of dailySuitablePeriodsDuration"
[8:ys3757-ib] unexpected disconnect completion event from dynamic process with rank=0 pg_id=kvs_4614_0 0x3407cc0
No traceback available
[1] "Done"
 *** caught segfault ***
address (nil), cause 'memory not mapped'

the disconnects happens at different times during execution, so far seems not to be a Soilwat problem
